config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :books do
    collection do
      get 'search_online'
      get 'search_scanner'
    end
  end

  resources :favorite_lists do
    member do
      post :post
      get 'edit_name'
      patch 'update_name'
      post 'add_book'
      get 'books'
      delete 'remove_book/:book_id', to: 'favorite_lists#remove_book', as: :remove_book
    end
  end

  resources :users, only: [:show, :edit, :update] do 
    member do
      post 'follow', to: 'users#follow'
      delete 'unfollow', to: 'users#unfollow'
      get 'following', to: 'users#following'
      get 'followers', to: 'users#followers'
    end
  end

  resources :posts, only: [:index, :show]
end

app/models/favorite_list.rb
class FavoriteList < ApplicationRecord
  belongs_to :user  # この行を追加
  validates :name, uniqueness: { scope: :user_id, massage: 'その名前のリストは既に存在します' }
  has_many :favorite_list_items, dependent: :destroy
  has_many :books, through: :favorite_list_items
end

app/controllers/favorite_lists_controller.rb
class FavoriteListsController < ApplicationController

  def new
    @favorite_list = FavoriteList.new
    @books = Book.all
  end

  def create
    @favorite_list = current_user.favorite_lists.build(favorite_list_params)
    if @favorite_list.save
      redirect_to @favorite_list
    else 
      @books = Book.all
      flash[:alert] = @favorite_list.errors.full_messages.join(', ')
      render 'new'
    end
  end

  def show
    @favorite_list = FavoriteList.find(params[:id])
    @books = @favorite_list.books

    respond_to do |format|
      format.html
      format.json { render json: @favorite_list.as_json(include: :books) }
    end
  end

  def edit
    @favorite_list = FavoriteList.includes(:books).find(params[:id])
  end

  def update
    @favorite_list = FavoriteList.find(params[:id])
    if @favorite_list.update(favorite_list_params)
      redirect_to @favorite_list, notice: 'お気に入りリストが正常に更新されました'
    else
      render :edit
    end
  end
  
  def index 
    @favorite_lists = current_user.favorite_lists
  end

  def add_book
    # 選択された本とお気に入りのリストを取得
    @book = Book.find(params[:book_id])
    favorite_list = FavoriteList.find(params[:id])
    @favorite_list = favorite_list
  
    # リストに本を追加
    unless favorite_list.books.include?(@book)
      favorite_list.books << @book
    end

    respond_to do |format|
      format.js { render 'add_book' }
      format.html { redirect_to favorite_list_path(favorite_list) }
    end
  end

  def books
    @favorite_list = FavoriteList.find(params[:favorite_list_id])
    @books = @favorite_list.books
    render partial: 'books_selection', collection: @books, as: :book
  end

  def remove_book
    @favorite_list = FavoriteList.find(params[:id])
    @book = Book.find(params[:book_id])
    @favorite_list.books.delete(@book)
  
    respond_to do |format|
      format.js { render 'remove_book' } # この行は変更が不要ですが、明示的に示しています
      format.html { redirect_to @favorite_list, notice: 'Book was successfully removed from the list.' }
    end
  end
  
  def destroy
    @favorite_list = FavoriteList.find(params[:id])
    @favorite_list.destroy
    redirect_to favorite_lists_path, notice: 'リストが正常に削除されました。'
  end

  def post
    @favorite_list = FavoriteList.find(params[:id])
    
    if @favorite_list.update(posted: true)
      redirect_to favorite_list_path(@favorite_list), notice: 'リストが投稿されました。'
    else
      redirect_to favorite_list_path(@favorite_list), alert: 'エラーが発生しました。'
    end
  end
  
  private 

  def favorite_list_params
    params.require(:favorite_list).permit(:name, :description, book_ids: [], books_attributes: [:id, :title, :author, :description, :recommended, :publisher, :published_date, :image_url])
  end

end

app/views/favorite_lists/add_book.js.erb
<!-- favorite_lists/add_book.js.erb -->

$('#books-list').append(`
  <div data-book-id="<%= j @book.id %>">
    <p>
      <% if @book.image_url.present? %>
        <img src="<%= j @book.image_url %>" alt="<%= j @book.title %>" class="book-image">
      <% end %>
      <strong>Title:</strong> <%= j @book.title %>
    </p>
    <!-- 他の本の情報もこちらに追加できます -->
    <a href="<%= j remove_book_favorite_list_path(@favorite_list, book_id: @book.id) %>" data-remote="true" data-method="delete">Remove from list</a>
    <hr>
  </div>
`);

// ページをリロード
window.location.reload(true);

app/views/favorite_lists/edit.html.erb
<%= form_for @favorite_list do |f| %>
  <!-- リスト名の編集 -->
  <h1>Edit List Name</h1>
  <%= f.label :name, "List Name:" %>
  <%= f.text_field :name %>
  <br><br>

  <!-- リストの説明の編集 -->
   <h2>Edit List Description</h2>
   <%= f.label :description, "List Description:" %>
   <%= f.text_area :description, rows: 5, placeholder: "リストの詳しい説明をこちらに入力してください。" %>
   <br><br>

  <!-- リスト内の本の一覧表示と削除機能 -->
  <h2>Books in the list:</h2>
  <% @favorite_list.books.each do |book| %>
    <div>
      <p>
        <% if book.image_url.present? %>
          <%= image_tag book.image_url, alt: book.title, class: 'book-image' %>
        <% end %>
        <strong>Title:</strong> <%= book.title %>
      </p>

      <p>
        <strong>Author:</strong> <%= book.author %>
      </p>

      <p>
        <strong>Description:</strong> <%= book.description %>
      </p>

      <p>
        <strong>Recommended:</strong> <%= book.recommended %>
      </p>

      <p>
        <strong>Publisher:</strong> <%= book.publisher %>
      </p>

      <p>
        <strong>Published date:</strong> <%= book.published_date %>
      </p>

      <%= link_to 'Remove from list', remove_book_favorite_list_path(@favorite_list, book_id: book.id), method: :delete, data: { confirm: 'Are you sure?' }, remote: true, class: "remove-book-link" %>
      <hr>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit "Update List", class: 'btn btn-success' %>
    <%= link_to '戻る', favorite_lists_path, class: 'btn btn-primary'%>  
  </div>
<% end %>

<!-- リストに新しい本を追加するためのドロップダウンメニュー -->
<h2>Add a book to the list:</h2>
<%= form_with url: add_book_favorite_list_path(@favorite_list), method: :post, local: false, id: "add-book-form" do |form| %>
  <%= form.collection_select :book_id, Book.all, :id, :title, prompt: "Choose a book" %>
  <%= form.submit 'Add to list', class: 'btn btn-primary' %>
<% end %>

app/views/favorite_lists/index.html.erb
<h1>お気に入りリスト一覧</h1>

<p>リストを選択してください:</p>

<select id="favorite_list_select">
  <option value="">-- リストを選択 --</option>
  <% @favorite_lists.each do |favorite_list| %>
    <option value="<%= favorite_list.id %>">
      <%= favorite_list.name %>
    </option>
  <% end %>
</select>

<script>
  // jQueryを使う場合
  $(document).ready(function(){
    $('#favorite_list_select').on('change', function(){
      var listId = $(this).val();
      
      if (listId) {
        window.location.href = "/favorite_lists/" + listId;
      }
    });
  });
</script>

app/views/favorite_lists/new.html.erb
<h1>リストを作成</h1>
<%= form_for @favorite_list do |f| %>
  <p>
    <%= f.label :name, "List Name" %>
    <%= f.text_field :name %>
  </p>
  
  <!-- リストの説明の編集 -->
   <h2>Edit List Description</h2>
   <%= f.label :description, "List Description:" %>
   <%= f.text_area :description, rows: 5, placeholder: "リストの詳しい説明をこちらに入力してください。" %>
   <br><br>

  <h2>リストから選択</h2>
  <% @books.each do |book| %>
    <%= render partial: 'books/book_selection', locals: { book: book, form: f } %>
  <% end %>

  <%= f.submit "登録" %>
<% end %>

app/views/favorite_lists/remove_book.js.erb
$(`#books-list div[data-book-id="<%= j @book.id %>"]`).remove();

// ページをリロード
window.location.reload(true);

app/views/favorite_lists/show.html.erb
<h1><%= @favorite_list.name %></h1>
<p>
   <strong>リストの説明:</strong>
   <%= @favorite_list.description %>
 </p>
<ul>
<% @favorite_list.books.each do |book| %>
  <li>
    <div>
      <p>
        <% if book.image_url.present? %>
          <%= image_tag book.image_url, alt: book.title, class: 'book-image' %>
        <% end %>
        <strong>Title:</strong>
        <%= book.title %>
      </p>

      <p>
        <strong>Author:</strong>
        <%= book.author %>
      </p>

      <p>
        <strong>Description:</strong>
        <%= book.description %>
      </p>

      <p>
        <strong>Recommended:</strong>
        <%= book.recommended %>
      </p>

      <p>
        <strong>Publisher:</strong>
        <%= book.publisher %>
      </p>

      <p>
        <strong>Published date:</strong>
        <%= book.published_date %>
      </p>
    </div>
  </li>
<% end %>
</ul>
 
 <!-- リストの最後にボタンを設置 -->
 <div class="list-actions">
    <%= link_to '戻る', favorite_lists_path, class: 'btn btn-primary'%>  
    <%= link_to '編集', edit_favorite_list_path(@favorite_list), class: 'btn btn-warning'%>
    <%= button_to '削除', favorite_list_path(@favorite_list), method: :delete, data: { confirm: 'この本をお気に入りから削除してもよろしいですか？' }, class: 'btn btn-danger' %>

    <% unless @favorite_list.posted? %>
    <%= button_to '投稿', post_favorite_list_path(@favorite_list), method: :post, data: { confirm: 'このリストを投稿してもよろしいですか？' }, class: 'btn btn-info' %>
  <% end %>
 </div>