config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :books do
    collection do
      get 'search_online'
      get 'search_scanner'
    end
  end

  resources :favorite_lists do
    member do
      post :post
      get 'edit_name'
      patch 'update_name'
      post 'add_book'
      get 'books'
      delete 'remove_book/:book_id', to: 'favorite_lists#remove_book', as: :remove_book
    end
  end

  resources :users, only: [:show, :edit, :update] do 
    member do
      post 'follow', to: 'users#follow'
      delete 'unfollow', to: 'users#unfollow'
      get 'following', to: 'users#following'
      get 'followers', to: 'users#followers'
    end
  end

  resources :posts, only: [:index, :show]
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :user
  has_many :favorite_list_items, dependent: :destroy
  has_many :favorite_lists, through: :favorite_list_items
  validates :title, uniqueness: { scope: [:user_id, :author], message: "既に登録済の書籍です" }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :name, presence: true
  validates :profile, length: { maximum:200 }

  # ActiveStorageの関連付け
  has_one_attached :avatar

  # Books association
  has_many :books

  has_many :favorite_lists, dependent: :destroy

  # follow
  has_many :active_follows, class_name: 'Follow', foreign_key: 'follower_id', dependent: :destroy
  has_many :passive_follows, class_name: 'Follow', foreign_key: 'followed_id', dependent: :destroy

  has_many :following, through: :active_follows, source: :followed 
  has_many :followers, through: :passive_follows, source: :follower

  def follow(other_user)
    unless self == other_user
      self.following << other_user
    end
  end

  # ユーザーのフォローを解除する
  def unfollow(other_user)
    self.following.delete(other_user)
  end

  # あるユーザーをフォローしているかどうかを確認する
  def following?(other_user)
    self.following.include?(other_user)
  end
end

app/controllers/books_controller.rb
require 'rest-client'  # HTTPartyを使用せずRestClientを使用する場合
require 'cgi'  # 日本語（非ASCII文字）のため

class BooksController < ApplicationController
  before_action :set_book, only: %i[show edit update destroy]

  BASE_URL = "https://www.googleapis.com/books/v1/volumes?maxResults=40&q="

  # GET /books or /books.json
  def index
    @books = current_user.books.distinct
    @favorite_lists = current_user.favorite_lists

  end

  # GET /books/1 or /books/1.json
  def show; end

  # GET /books/new
  def new
    if params[:title]
      @book = Book.new(
        title: params[:title],
        author: params[:author],
        publisher: params[:publisher],
        published_date: params[:published_date],
        image_url: params[:image_url]
      )
    else
      @book = Book.new
    end
  end
  

  # GET /books/1/edit
  def edit; end

  # POST /books or /books.json
  def create
    @book = current_user.books.build(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  # GET /books/search_online
  def search_online
    # ISBNベースの検索
    if params[:isbn].present?
      isbn = params[:isbn]
      response = RestClient.get "https://www.googleapis.com/books/v1/volumes?q=isbn:#{isbn}"
      @online_books = JSON.parse(response.body)["items"]
      
      # 最初の1件だけを取得
      @online_books = [@online_books.first] if @online_books
    
    # キーワードベースの検索
    elsif params[:keyword].present?
      encoded_keyword = CGI.escape(params[:keyword])
      response = RestClient.get("#{BASE_URL}#{encoded_keyword}")
      @online_books = JSON.parse(response.body)["items"]
    end
  end

  # search_scannerの設定
  def search_scanner
    @book = Book.new
  end
    
  private

  # Use callbacks to share common setup or constraints between actions.
  def set_book
    @book = Book.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def book_params
    params.require(:book).permit(:title, :author, :description, :recommended, :publisher, :published_date, :image_url)
  end

  def book_params_from_search
    params.permit(:title, :author, :publisher, :published_date, :image_url)
  end
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p>

  <p>
    <strong>Recommended:</strong>
    <%= book.recommended %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= book.publisher %>
  </p>

  <p>
    <strong>Published date:</strong>
    <%= book.published_date %>
  </p>

</div>

app/views/books/_book_selection.html.erb
<div id="<%= dom_id book %>">
  <%= form.check_box :book_ids, { multiple: true }, book.id, nil %>
  
  <p>
    <% if book.image_url.present? %>
      <%= image_tag book.image_url, alt: book.title, class: 'book-image' %>
    <% end %>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Author:</strong>
    <%= book.author %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p>

  <p>
    <strong>Recommended:</strong>
    <%= book.recommended %>
  </p>

  <p>
    <strong>Publisher:</strong>
    <%= book.publisher %>
  </p>

  <p>
    <strong>Published date:</strong>
    <%= book.published_date %>
  </p>
</div>

app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= form.label :image_url, "Image URL" %>
  <%= form.text_field :image_url %>
  </div>

  <div>
    <%= form.label :title, style: "display: block" %>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :author, style: "display: block" %>
    <%= form.text_field :author %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div>
    <%= form.label :recommended, style: "display: block" %>
    <%= form.check_box :recommended %>
  </div>

  <div>
    <%= form.label :publisher, style: "display: block" %>
    <%= form.text_field :publisher %>
  </div>

  <div>
    <%= form.label :published_date, style: "display: block" %>
    <%= form.date_field :published_date %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<h1>Editing book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Show this book", @book %> |
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Your Books</h1>

<div id="books">
  <% @books.each do |book| %>
    <%= render book %>
    <p>
      <% if book.image_url.present? %>
        <%= image_tag book.image_url, alt: book.title, class: 'book-image' %>
      <% end %>
      <%= link_to "Show this book", book %>
    </p>
  <% end %>
</div>

<%= link_to "New book", new_book_path %>

app/views/books/new.html.erb
<h1>New book</h1>

<br>
<%# オンライン検索フォームの追加 %>
<div>
  <%= form_tag(search_online_books_path, method: "get", id: "search_online_form") do%>
     <%= text_field_tag :keyword, nil, placeholder: "キーワードで検索" %>

    <%# ISBNを格納するための隠しフィールド %>
    <%= hidden_field_tag :isbn, nil, id: 'isbn_hidden_field' %>
  
     <%= submit_tag "検索", class: "btn btn-primary" %>
  <% end %>
</div>

<%= render "form", book: @book %>

app/views/books/search_online.html.erb
<%= form_with(url: search_online_books_path, method: :get) do |form| %>
  <%= form.text_field :keyword %>
  <%= form.submit "Search Online" %>
<% end %>

<% if @online_books %>
  <% @online_books.each do |book| %>
   <div class="book-result">
    <h3><%= book["volumeInfo"]["title"] %></h3>
    <p><%= book["volumeInfo"]["authors"]&.join(', ') %></p>
    <p><%= book["volumeInfo"]["publisher"] %></p>
    <p><%= book["volumeInfo"]["publishedDate"] %></p>
    <%= image_tag book["volumeInfo"]["imageLinks"]["thumbnail"] if book["volumeInfo"]["imageLinks"] %>

    <%= form_with(url: new_book_path, method: :get, html: { class: 'select-book-form' }) do |f| %>
      <%= f.hidden_field :title, value: book["volumeInfo"]["title"] %>
      <%= f.hidden_field :author, value: book["volumeInfo"]["authors"]&.join(', ') %>
      <%= f.hidden_field :publisher, value: book["volumeInfo"]["publisher"] %>
      <%= f.hidden_field :published_date, value: book["volumeInfo"]["publishedDate"] %>
      <%= f.hidden_field :image_url, value: book["volumeInfo"]["imageLinks"]["thumbnail"] if book["volumeInfo"]["imageLinks"] %>
      <!-- 必要な他のフィールドも追加することができます -->

        <%= f.submit "この書籍を選択", class: "btn btn-secondary" %>
      <% end %> 
  <% end %>
<% end %>

app/views/books/search_scanner.html.erb
<h1>New book</h1>

<%= form_for @book do |f| %>
  <%# フォームの詳細部分を表示する部分 %>
  <div>
    <%= f.text_field :title, placeholder: "Title", id: "book-title-input" %>
    <%= f.text_field :author, placeholder: "Author", id: "book-author-input" %>
    <%= f.text_field :publisher, placeholder: "Publisher", id: "book-publisher-input" %>
    <%= f.text_field :published_date, placeholder: "Published Date", id: "book-published-date-input" %>
    <%= f.hidden_field :image_url, id: "book-image-url-input" %>
  </div>
  
  <div>
    <img id="book-cover" src="" alt="Book Cover" style="max-width: 200px; display: none;">
  </div>

  <div>
    <%= f.submit "登録", class: "btn btn-primary" %>
  </div>
<% end %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
  <div id="scanner"></div>
</div>

<script src="https://cdn.jsdelivr.net/npm/quagga@0.12.1/dist/quagga.min.js"></script>
<script>
  function setBookDetailsToForm(details) {
    document.getElementById('book-title-input').value = details.title || '';
    document.getElementById('book-author-input').value = details.authors ? details.authors.join(', ') : '';
    document.getElementById('book-publisher-input').value = details.publisher || '';
    document.getElementById('book-published-date-input').value = details.publishedDate || '';
    if (details.imageLinks && details.imageLinks.thumbnail) {
      const bookCover = document.getElementById('book-cover');
      const imageUrlInput = document.getElementById('book-image-url-input');
      bookCover.src = details.imageLinks.thumbnail;
      imageUrlInput.value = details.imageLinks.thumbnail; // カバー画像のURLを隠しフィールドにセット
      bookCover.style.display = 'block';
    }
  }

  function fetchBookDetails(isbn) {
    const API_ENDPOINT = `https://www.googleapis.com/books/v1/volumes?q=isbn:${isbn}`;
    fetch(API_ENDPOINT)
    .then(response => response.json())
    .then(data => {
      if (data.totalItems > 0) {
        const bookDetails = data.items[0].volumeInfo;
        setBookDetailsToForm(bookDetails);
      } 
      // else {
      //   alert('No book found for the scanned ISBN.');
      // }
    })
    .catch(error => {
      console.error('Error fetching book details:', error);
    });
  }

  if (document.querySelector('#scanner')) {
    Quagga.init({
      inputStream: {
        name: "Live",
        type: "LiveStream",
        target: document.querySelector('#scanner')
      },
      decoder: {
        readers: ["ean_reader"]
      }
    }, function(err) {
      if (err) {
        console.log(err);
        return;
      }
      Quagga.start();
    });

    Quagga.onDetected(function(result) {
      try {
        const isbn = result.codeResult.code;
        if(isbn.length === 10 || isbn.length === 13) {
          fetchBookDetails(isbn);
        } else {
          console.log('Scanned barcode is not a valid ISBN:', isbn);
        }
      } catch (error) {
        console.error('Error during detection:', error);
      }
    });
  }
</script>

app/views/books/show.html.erb
<p style="color: green"><%= notice %></p>

<% if @book.image_url.present? %>
  <%= image_tag @book.image_url, alt: @book.title, class: 'book-image' %>
<% end %>


<%= render @book %>

<div>
  <%= link_to "Edit this book", edit_book_path(@book) %> |
  <%= link_to "Back to books", books_path %>

  <%= button_to "Destroy this book", @book, method: :delete %>
</div>