config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :books do
    collection do
      get 'search_online'
      get 'search_scanner'
    end
  end

  resources :favorite_lists do
    member do
      post :post
      get 'edit_name'
      patch 'update_name'
      post 'add_book'
      get 'books'
      delete 'remove_book/:book_id', to: 'favorite_lists#remove_book', as: :remove_book
    end
  end

  resources :users, only: [:show, :edit, :update] do 
    member do
      post 'follow', to: 'users#follow'
      delete 'unfollow', to: 'users#unfollow'
      get 'following', to: 'users#following'
      get 'followers', to: 'users#followers'
    end
  end

  resources :posts, only: [:index, :show]
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posted_favorite_lists = FavoriteList.includes(:user).where(posted: true)

    # キーワードによる検索が存在する場合
    if params[:search].present?
      @posted_favorite_lists = @posted_favorite_lists.where("name LIKE ?", "%#{params[:search]}%")
    end

    # ユーザーによる絞り込みが存在する場合
    if params[:user_id].present?
      @posted_favorite_lists = @posted_favorite_lists.where(user_id: params[:user_id])
    end
  end

  def show
    @favorite_list = FavoriteList.find(params[:id])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/index.html.erb
<h1>投稿一覧</h1>

<%= form_with url: posts_path, method: :get, local: true do %>
  <%= label_tag :search, "キーワード検索:" %>
  <%= text_field_tag :search, params[:search] %>

  <%= label_tag :user_id, "ユーザーを選択:" %>
  <%= select_tag :user_id, options_from_collection_for_select(current_user.following, "id", "name", params[:user_id]), include_blank: "全てのユーザー" %>
  
  <%= submit_tag "絞り込む", name: nil %>
<% end %>

<% @posted_favorite_lists.each do |list| %>
  <h2>
   <%= link_to list.name, post_path(list) %> 
    (投稿者: <%= list.user.name %> 
    <% unless current_user.following.include?(list.user) %>
      <%= button_to 'フォローする', follow_user_path(list.user), method: :post, class: 'btn btn-primary' %>
    <% else %>
      <%= button_to 'フォローを外す', unfollow_user_path(list.user), method: :delete, class: 'btn btn-danger' %>
    <% end %> 
    投稿日時： <%= list.created_at.strftime('%Y-%m-%d %H:%M:%S') %>)
  </h2>
  <p><strong>リストの説明:</strong> <%= list.description %></p>
  <ul>
    <% list.books.each do |book| %>
      <li>
        <div>
          <p>
            <% if book.image_url.present? %>
              <%= image_tag book.image_url, alt: book.title, class: 'book-image' %>
            <% end %>
            <strong>Title:</strong> <%= book.title %>
          </p>
        </div>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/posts/show.html.erb
<h1><%= @favorite_list.name %></h1>
 <strong>リストの説明:</strong>
   <%= @favorite_list.description %>
 <ul>
 <% @favorite_list.books.each do |book| %>
   <li>
     <div>
       <p>
         <% if book.image_url.present? %>
           <%= image_tag book.image_url, alt: book.title, class: 'book-image' %>
         <% end %>
         <strong>Title:</strong>
         <%= book.title %>
       </p>

       <p>
         <strong>Author:</strong>
         <%= book.author %>
       </p>

       <p>
         <strong>Description:</strong>
         <%= book.description %>
       </p>

       <p>
         <strong>Recommended:</strong>
         <%= book.recommended %>
       </p>

       <p>
         <strong>Publisher:</strong>
         <%= book.publisher %>
       </p>

       <p>
         <strong>Published date:</strong>
         <%= book.published_date %>
       </p>
     </div>
   </li>
 <% end %>
 </ul>

 <!-- リストの最後にボタンを設置 -->
 <div class="list-actions">
   <%= link_to '戻る', posts_path, class: 'btn btn-primary' %>  
 </div>