config/routes.rb
Rails.application.routes.draw do
  root to: 'posts#index'
  
  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :books do
    collection do
      get 'search_online'
      get 'search_scanner'
    end
  end

  resources :favorite_lists do
    member do
      post :post
      get 'edit_name'
      patch 'update_name'
      post 'add_book'
      get 'books'
      delete 'remove_book/:book_id', to: 'favorite_lists#remove_book', as: :remove_book
    end
  end

  resources :users, only: [:show, :edit, :update] do 
    member do
      post 'follow', to: 'users#follow'
      delete 'unfollow', to: 'users#unfollow'
      get 'following', to: 'users#following'
      get 'followers', to: 'users#followers'
    end
  end

  resources :posts, only: [:index, :show]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <!-- titleを変更します -->
    <title>Book App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!-- Style追加 -->
    <link rel="stylesheet" href="<%= mix('/css/app.css') %>">
    <!-- Javascript追加 -->
    <script src="<%= mix('/js/bootstrap.js') %>"></script>
    <!-- turbo.jsを追加します -->
  <%# <script src="<%= mix('/js/turbo.js') %>"></script> %>
  <%# <%= javascript_include_tag 'favorite_lists' %> %>
    <%# <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %> %>
  </head>

  <body>
    <div class="main-container">
      <!--  ナビゲーションバーの追加 -->
      <nav class="custom-navbar">
        <div id="menuToggle">
          <input type="checkbox" />
          <span></span>
          <span></span>
          <span></span>
          <ul id="menu">
          <!-- ここから追加-->
          <% if user_signed_in? %>
            <!-- ログインしている場合に表示されます -->
            <!-- user_signed_in? は device が提供している認証済みかを判定するメソッドです -->
            <li>
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "書籍一覧", "/", class: "nav-link" %>
            </li>
            <li>
              <%= link_to "投稿一覧", posts_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "キーワードでさがす", new_book_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "バーコードでさがす", search_scanner_books_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "リストを作成",new_favorite_list_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "リストを表示", favorite_lists_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "ユーザー情報", user_path(current_user), class: "nav-link" %>
            </li>
            <li>
              <%= link_to "ユーザー情報編集", edit_user_path(current_user), class: "nav-link" %>
            </li>

          <% else %>
            <!-- ログインしていない場合に表示されます -->
            <!-- else 以降は前述のif文の否定になります -->
            <li>
              <%= link_to "新規登録", new_user_registration_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "ログイン", new_user_session_path, class: "nav-link" %>
            </li>
          <% end %>
          <!-- ここまで-->  
          </ul>
        </div>
      </nav>

      <!-- アラートメッセージの追加 -->
      <% if notice %>
        <div class="alert alert-success" role="alert">
          <%= notice %>
        </div>
      <% end %>
      <% if alert %>
        <div class="alert alert-danger" role="alert">
          <%= alert %>
        </div>
      <% end %>

      <div class="bg-white text-dark">
        <%= yield %>
      </div>
    </div>

   
  </body>
</html>